#baseURL = 'https://dyson-wang.github.io/'
baseURL = 'http://172.21.15.52/'
# languageCode = 'en-us'
languageCode = 'zh-cn'
title = "ivy"
hasCJKLanguage = true
paginate = 18
enableGitInfo = true
disqusShortname = ""  # "dysonivy"

[mediaTypes.'application/x-ndjson']
  suffixes = ['ndjson']

[outputs]
  home = ["HTML", "Algolia"]

[outputFormats]
  [outputFormats.Algolia]
    baseName = 'algolia'
    isPlainText = true
    notAlternative = true
    mediaType = 'application/x-ndjson'

[Params]
  description = "Dyson's Blogs"
  
  omitCategoryOnMenu = false
  categoryName = "Category"
  
  showCodeCopyButton = true
  disableToTop = false
  disableToBottom = false
  enableSearch = false
  enableHighlight = true
  enableComments = false

  [Params.head]
    # 自定义css放在assets
    customCSS = "css/custom.css"

  [Params.home]
    # 展出最新的四篇文章或者设置'IsPage=true' 可以用逗号隔开
    showContentTypes = ["banner"]

  [Params.app]
    # 当添加到 iOS 主屏幕或 Android 启动程序时，应用程序的可选站点标题覆盖
    title = "Dyson ivy"
    # 是否省略图标资源链接
    noFavicon = false
    # 使用现代 SVG 图标代替旧的样式.png 和.ico 文件
    favicon = "/favicon.ico"
    # Safari mask icon color
    iconColor = "#ffffff"
    # Android browser theme color
    themeColor = "#ffffff"

  [Params.logo]
    # Image logo or Text logo
    # Recommended to set image as logo. (prefer)
    img = "/images/black_17.svg"
    img_dark = "/images/white_17.svg"

    # max height not greater than 56 (px). default: 56 (px)
    customLogoHeight = '56'
    customLogoWidth = '56'
    text = "ivy"

  # Copyright 
  [Params.copyright]
    owner = "Dyson Wang"
    start_year = "2024"

  # Article Meta
  [Params.articleMeta]
    enableAuthor = true
    disableDate = false
    disableModifiedDate = false
    disableCountWords = false
    disableReadTime = false
    disableHero = false
    disableToc = false

    # Note: only works if waline or twikoo is enabled.
    enablePageView = true
  
  # 社交图标
  [Params.society]
    # 自定义eg: Add "extra_social.html" in the "layout/partials/" directory of your project.
    customSocial = "extra_social.html"

    [Params.society.email]
      enable = true
      url = "dyson.wang@outlook.com"
    [Params.society.github]
      enable = true
      url = "https://github.com/Dyson-Wang"
    [Params.society.facebook]
      enable = true
      url = ""
    [Params.society.x]  # old twitter
      enable = true
      url = ""
    [Params.society.wechat]
      enable = true
      OrcodeUrl = ["/images/society/wechat/wechat.png"]

  # Search-Algolia
  [Params.algolia]
    # Type of content. see: https://gohugo.io/content-management/types/
    type = ["posts"]
    # like pages variables. see: https://gohugo.io/variables/page/
    vars = ["title", "description", "permalink"]
    # Front Matter Variables. 
    # see: https://gohugo.io/content-management/front-matter/#front-matter-variables
    params = ["tags"]

    # app_id = "995JRM5ZAU"
    # api_key = "4a1095e4b8c96d2baee42d4c64b16afa"
    index = "hugo_theme_seven_demo"
    # see: https://www.algolia.com/doc/api-reference/widgets/snippet/js/#about
    snippet_attr = "description"
    # see: https://www.algolia.com/doc/api-reference/widgets/highlight/js/#examples
    highlight_attr = "title"
  
  # Comments
  [Params.comment]
    enable = false
    # Note: only works if waline or twikoo is enabled.
    enableCounts = false
    [Params.comment.waline]
      enable = false
      serverURL = "https://seven-demo.comment.supcat.cn/.netlify/functions/comment"
      lang = "en"
      reaction = true
      search = true
    [Params.comment.twikoo]
      enable = false
      envID = "https://celebrated-youtiao-8a8d79.netlify.app/.netlify/functions/twikoo"
      path = ""
      lang = "en"
      region = ""
  
  # Analytics
  [Params.analytics]
    [Params.analytics.goatcounter]
      enable = false
      # code = "seven-demo"  

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = false

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2

[menu]
  [[menu.main]]
    name = "About"
    pre = ""
    url = "/banner/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Archive"
    url = "/archive"
    weight = 30
  [[menu.main]]
    name = "Goods"
    pre = ""
    url = "/goods/"
    weight = 40
  [[menu.main]]
    name = "Releases"
    pre = "releases"
    weight = 50
  [[menu.main]]
    identifier = "comments-with-waline"
    name = 'with waline'
    # url = 'https://seven-demo.supcat.cn/'
    url = '/'
    parent = 'Releases'
    weight = 1
  [[menu.main]]
    name = 'with twikoo'
    url = '/'
    parent = 'Releases'
    weight = 2

[module]
  # It is recommended that Chinese users modify the proxy configuration
  # proxy = 'https://goproxy.cn,direct'
  # workspace = 'on'
  [[module.imports]]
    path = 'github.com/mrhelloboy/seven'
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  noJSConfigInAssets = true
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
